language: node_js

cache: npm

install:
  - npm install

script:
  - npm test

jobs:
  include:
    - stage: 'Build'
      script: npm install

    - stage: 'Test'
      name: 'Lint'
      script: npm run lint
    - script: npm run test:coverage
      name: 'Test'
    - script: jest --coverage && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
      nme: 'Coverage'

    - stage: deploy
      name: 'Deploy'
      script: echo 'Deploy'

stages:
  - build
  - test
  - name: deploy
    if: (branch = master)
