version: "3"
services:
  graphql:
    build: .
    ports:
      - "9900:9900"
    volumes:
      - ${CONFIG_FILE}:/src/config/default.json
    links:
      - redis
  redis:
    image: redis
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]
#    volumes:
#      - release-status-redis-volume:/data
#volumes:
#  release-status-redis-volume:
